trainer: forces

dataset:
  - src: /Users/irmakaslan/Documents/Personal-Code-Files/ocp/data/s2ef/200k/train/data.lmdb
    normalize_labels: True
    target_mean: -0.7554450631141663
    target_std: 2.887317180633545
    grad_target_mean: 0.0
    grad_target_std: 2.887317180633545
  - src: /Users/irmakaslan/Documents/Personal-Code-Files/ocp/data/s2ef/200k/train/data.lmdb
  - src: /Users/irmakaslan/Documents/Personal-Code-Files/ocp/data/s2ef/200k/train/data.lmdb

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
